services:
  db:
    image: postgres:18.0-alpine3.21
    restart: always
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
