name: ci

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
              java-version: '23'
              distribution: 'zulu'
        - name: Set up sbt
          uses: sbt/setup-sbt@v1      
        - name: Cache SBT
          uses: actions/cache@v2
          env:
            ACTIONS_STEP_DEBUG: true
          with:
              path: |
                    ~/.ivy2/cache
                    ~/.ivy2/local
                    ~/.sbt
                    ~/.coursier
                    ~/.cache/coursier
                    ~/.cache/ivy2
              key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/*.scala', 'project/*.sbt') }}
              restore-keys: |
                    ${{ runner.os }}-sbt-

        - name: Run SBT compile
          run: ./scripts/setup.sh

